In [ ]:
# Import the data from SQL.

import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:123456@localhost:5432/crop_data")

df = pd.read_sql("SELECT * FROM crop_data_cleaned", engine)

df.head()

          Area               Item  Year  Area harvested  Production   Yield
0  Afghanistan  Almonds, in shell  2019         29203.0     38205.0  1308.3
1  Afghanistan  Almonds, in shell  2020         22134.0     39307.0  1775.9
2  Afghanistan  Almonds, in shell  2021         36862.0     64256.0  1743.2
3  Afghanistan  Almonds, in shell  2022         36462.0     63515.0  1742.0
4  Afghanistan  Almonds, in shell  2023         37000.0     67000.0  1810.8

In [ ]:
# Encode the datas.

from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in ["Area", "Item"]:
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])
    encoders[col] = encoder

In [ ]:
# Independent variables.

x = df.drop(['Production'],axis = 1)

# Dependent variable.

y = df['Production']

In [4]:
x.head()

   Area  Item  Year  Area harvested   Yield
0     0     2  2019         29203.0  1308.3
1     0     2  2020         22134.0  1775.9
2     0     2  2021         36862.0  1743.2
3     0     2  2022         36462.0  1742.0
4     0     2  2023         37000.0  1810.8

In [5]:
y.head()

0    38205.0
1    39307.0
2    64256.0
3    63515.0
4    67000.0
Name: Production, dtype: float64

In [ ]:
# Spilt the data for train and test.

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Ridge Model
ridge = Ridge(alpha=1.0)
ridge.fit(x_train, y_train)

ridge_pred = ridge.predict(x_test) 

print("Ridge MAE:", mean_absolute_error(y_test, ridge_pred))
print("Ridge R2:", r2_score(y_test, ridge_pred))


# Lasso Model
lasso = Lasso(alpha=0.1)
lasso.fit(x_train, y_train)

lasso_pred = lasso.predict(x_test)

print("Lasso MAE:", mean_absolute_error(y_test, lasso_pred))
print("Lasso R2:", r2_score(y_test, lasso_pred))

#decision tree
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)

dt_pred = dt.predict(x_test)

print("Decision Tree MAE:", mean_absolute_error(y_test, dt_pred))
print("Decision Tree R2:", r2_score(y_test, dt_pred))


#random forest
random = RandomForestRegressor()
random.fit(x_train, y_train)

random_pred = random.predict(x_test)

print("random forest MAE:", mean_absolute_error(y_test, random_pred))
print("random forest R2:", r2_score(y_test, random_pred))

Ridge MAE: 1161402.283023687
Ridge R2: 0.5904025839799144
Lasso MAE: 1161402.2838549323
Lasso R2: 0.590402583952008
Decision Tree MAE: 56718.69281315994
Decision Tree R2: 0.9911072029705453
random forest MAE: 43932.420398277165
random forest R2: 0.9946512620413497

In [ ]:
# Store the model and encoder.

import joblib

joblib.dump(encoders, "encoded_data.pkl")
joblib.dump(random, "random_forest.pkl")

['random_forest.pkl']